name: WebdriverIO Tests with Allure Reports

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow on

jobs:
  test:
    name: Run WebdriverIO Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Adjust this to your Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Run Tests and Generate Allure Reports
        run: |
          npm test
          npx allure generate --clean

      - name: Publish Allure Reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report  # Adjust this to the directory where your Allure reports are generated
